kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: admin-user
subjects:
  - kind: User
    name: admin@entercloud.info
  - kind: ServiceAccount
    namespace: tectonic-system
    name: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
